name: Run bash script
run-name: run bash script
on: [push]
jobs:
  run_bash_script:
    defaults:
      run:
        shell: bash
        working-directory: /blenderToMitsuba
    runs-on: ubuntu-latest
    steps:
      - name: checkout to code
        uses: actions/checkout@main
      - name: run setup script
        run: |
          echo "test1"
          whereis setup.sh
          sh setup.sh