name: blender_scripting
run-name: intall and run blender
on: [push]
jobs:
  run_bash_script:
    defaults:
      run:
        shell: bash
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - name: checkout to code
        uses: actions/checkout@main
      - name: run blender setup script
        run: |
          sh setup.sh